export const workspaceCopy = {
  zh: {
    space: "我的空间",
    today: "今天",
    records: "记录",
    explore: "回顾",
    charts: "我的命盘",
    settings: "账户与设置",
    website: "查看官网",
    feedback: "反馈",
    greeting: "留一点时间，听听自己。",
    todayBody: "记下今天发生的事，也记下当时的心情。开心、疲惫、委屈，都可以留下来。",
    recordsBody: "每条记录都会带上当天的干支，Sign Atlas 正是这样学会你的顺日。",
    exploreBody: "选一天，请 AI 从八字、Vedic 和塔罗三个视角解读，并给你一个可以尝试的小行动。",
    chartBody: "出生资料、命盘和深度报告，组成你的个人探索档案。",
    context: "这次探索的起点",
    continue: "请 AI 一起回顾这一天",
    recent: "最近的生活",
    all: "查看全部记录",
    choose: "选择一篇记录",
    noEntry: "先记录一件你想理解的事，再从这里开始探索。",
    write: "写一条记录",
    deep: "新建 Vedic 读盘",
    bazi: "新建八字命盘 · 预览",
    returnCharts: "返回我的命盘",
    discard: "有尚未保存的记录，确定离开吗？",
    resume: "继续读盘",
    chartLink: "查看命盘与报告",
    sources: "展开三种视角与行动",
    emptyReports: "你的第一份命盘，从出生资料开始。",
    savedContext: "已保存的记录",
    personal: "属于你的生活档案",
    dailyFacts: "今天的历法",
    homeAction: "进入我的空间"
  },
  en: {
    space: "My space",
    today: "Today",
    records: "Journal",
    explore: "Reflect",
    charts: "My charts",
    settings: "Account & settings",
    website: "Visit website",
    feedback: "Feedback",
    greeting: "A little space to listen to yourself.",
    todayBody:
      "Write down what happened and how it felt. Joy, tiredness and difficult moments all have a place.",
    recordsBody:
      "Every day you log carries its stem-branch. That's how Sign Atlas learns your auspicious days.",
    exploreBody:
      "Pick a day and let AI read it through BaZi, Vedic and Tarot, with one small thing to try.",
    chartBody: "Your birth details, charts and in-depth readings in one place.",
    context: "The starting point",
    continue: "Reflect on this day with AI",
    recent: "Recent moments",
    all: "All entries",
    choose: "Choose an entry",
    noEntry: "Capture something you want to understand, then explore it here.",
    write: "Write an entry",
    deep: "New Vedic reading",
    bazi: "New BaZi chart · Preview",
    returnCharts: "Back to my charts",
    discard: "Leave without saving this entry?",
    resume: "Continue reading",
    chartLink: "View charts & reports",
    sources: "Three perspectives & actions",
    emptyReports: "Your first chart starts with your birth details.",
    savedContext: "Saved entry",
    personal: "Your life, in perspective",
    dailyFacts: "Today's calendar",
    homeAction: "Enter my space"
  },
  ja: {
    space: "マイスペース",
    today: "今日",
    records: "記録",
    explore: "ふりかえり",
    charts: "マイチャート",
    settings: "アカウント設定",
    website: "公式サイト",
    feedback: "ご意見",
    greeting: "自分の声を聴く、ひととき。",
    todayBody: "今日の出来事と、そのときの気持ちを記録。喜びも疲れも、つらかった瞬間も残せます。",
    recordsBody:
      "記録した日にはその日の干支が付きます。こうして Sign Atlas はあなたの吉日を学びます。",
    exploreBody:
      "具体的な出来事を AI と話し、気持ちを整理して、伝統文化の視点から小さな行動を考えましょう。",
    chartBody: "出生情報、チャート、詳しいレポートをまとめて管理。",
    context: "今回の探索の出発点",
    continue: "AI とこの日をふりかえる",
    recent: "最近の記録",
    all: "すべての記録",
    choose: "記録を選ぶ",
    noEntry: "理解したい出来事を記録してから、探索を始めましょう。",
    write: "記録を書く",
    deep: "Vedic リーディングを作成",
    bazi: "八字チャート · プレビュー",
    returnCharts: "マイチャートに戻る",
    discard: "保存せずに移動しますか？",
    resume: "続きを見る",
    chartLink: "チャートとレポート",
    sources: "3つの視点と行動",
    emptyReports: "最初のチャートは出生情報から。",
    savedContext: "保存した記録",
    personal: "あなたの生活の記録",
    dailyFacts: "今日の暦",
    homeAction: "マイスペースへ"
  }
} as const;

// Only local workspace destinations may be used after authentication.
export function safeWorkspaceReturn(value: string | null): string {
  return value && /^\/app(?:\/|\?|$)/.test(value) && !/[\\\r\n]/.test(value) ? value : "/app";
}
