export const workspaceCopy = {
  zh: {
    space: "我的空间",
    today: "今天",
    records: "记录",
    explore: "探索",
    charts: "我的命盘",
    settings: "账户与设置",
    website: "查看官网",
    greeting: "留一点时间，听听自己。",
    todayBody: "从一件小事开始。你的记录、探索和命盘，都在这里。",
    recordsBody: "回看生活里的细节，慢慢发现属于自己的节奏。",
    exploreBody: "带着一件具体的事，从不同视角继续理解自己。",
    chartBody: "出生资料、命盘和深度报告，组成你的个人探索档案。",
    context: "这次探索的起点",
    continue: "探索这件事",
    recent: "最近的生活",
    all: "查看全部记录",
    choose: "选择一篇记录",
    noEntry: "先记录一件你想理解的事，再从这里开始探索。",
    write: "写一条记录",
    deep: "新建 Vedic 读盘",
    bazi: "新建八字命盘 · 预览",
    returnCharts: "返回我的命盘",
    discard: "有尚未保存的记录，确定离开吗？",
    resume: "继续读盘",
    chartLink: "查看命盘与报告",
    sources: "展开三种视角与行动",
    emptyReports: "你的第一份命盘，从出生资料开始。",
    savedContext: "已保存的记录",
    personal: "属于你的生活档案",
    dailyFacts: "今天的历法",
    homeAction: "进入我的空间"
  },
  en: {
    space: "My space",
    today: "Today",
    records: "Journal",
    explore: "Explore",
    charts: "My charts",
    settings: "Account & settings",
    website: "Visit website",
    greeting: "A little space to listen to yourself.",
    todayBody: "Start with one small moment. Your journal, reflections and charts belong here.",
    recordsBody: "Revisit the details. Discover your own rhythms over time.",
    exploreBody: "Bring a real moment and explore it through different perspectives.",
    chartBody: "Your birth details, charts and in-depth readings in one place.",
    context: "The starting point",
    continue: "Explore this moment",
    recent: "Recent moments",
    all: "All entries",
    choose: "Choose an entry",
    noEntry: "Capture something you want to understand, then explore it here.",
    write: "Write an entry",
    deep: "New Vedic reading",
    bazi: "New BaZi chart · Preview",
    returnCharts: "Back to my charts",
    discard: "Leave without saving this entry?",
    resume: "Continue reading",
    chartLink: "View charts & reports",
    sources: "Three perspectives & actions",
    emptyReports: "Your first chart starts with your birth details.",
    savedContext: "Saved entry",
    personal: "Your life, in perspective",
    dailyFacts: "Today's calendar",
    homeAction: "Enter my space"
  },
  ja: {
    space: "マイスペース",
    today: "今日",
    records: "記録",
    explore: "探索",
    charts: "マイチャート",
    settings: "アカウント設定",
    website: "公式サイト",
    greeting: "自分の声を聴く、ひととき。",
    todayBody: "小さな出来事から。記録、振り返り、チャートを一つの場所に。",
    recordsBody: "日々を振り返り、自分のリズムを見つけましょう。",
    exploreBody: "具体的な出来事を、異なる視点から考えましょう。",
    chartBody: "出生情報、チャート、詳しいレポートをまとめて管理。",
    context: "今回の探索の出発点",
    continue: "この出来事を探索",
    recent: "最近の記録",
    all: "すべての記録",
    choose: "記録を選ぶ",
    noEntry: "理解したい出来事を記録してから、探索を始めましょう。",
    write: "記録を書く",
    deep: "Vedic リーディングを作成",
    bazi: "八字チャート · プレビュー",
    returnCharts: "マイチャートに戻る",
    discard: "保存せずに移動しますか？",
    resume: "続きを見る",
    chartLink: "チャートとレポート",
    sources: "3つの視点と行動",
    emptyReports: "最初のチャートは出生情報から。",
    savedContext: "保存した記録",
    personal: "あなたの生活の記録",
    dailyFacts: "今日の暦",
    homeAction: "マイスペースへ"
  }
} as const;

// Only local workspace destinations may be used after authentication.
export function safeWorkspaceReturn(value: string | null): string {
  return value && /^\/app(?:\/|\?|$)/.test(value) && !/[\\\r\n]/.test(value) ? value : "/app";
}
