"""initial schema

Revision ID: 73b62eebd34b
Revises:
Create Date: 2026-08-05 19:20:16.994481
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '73b62eebd34b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clerk_user_id', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=240), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_clerk_user_id'), 'app_users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=False)
    op.create_index(op.f('ix_app_users_role'), 'app_users', ['role'], unique=False)
    op.create_index(op.f('ix_app_users_updated_at'), 'app_users', ['updated_at'], unique=False)
    op.create_table('billing_checkouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=120), nullable=False),
    sa.Column('checkout_id', sa.String(length=120), nullable=True),
    sa.Column('owner_user_id', sa.String(length=160), nullable=False),
    sa.Column('plan_key', sa.String(length=80), nullable=False),
    sa.Column('creem_product_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_checkouts_checkout_id'), 'billing_checkouts', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_billing_checkouts_creem_product_id'), 'billing_checkouts', ['creem_product_id'], unique=False)
    op.create_index(op.f('ix_billing_checkouts_owner_user_id'), 'billing_checkouts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_billing_checkouts_plan_key'), 'billing_checkouts', ['plan_key'], unique=False)
    op.create_index(op.f('ix_billing_checkouts_request_id'), 'billing_checkouts', ['request_id'], unique=True)
    op.create_index(op.f('ix_billing_checkouts_status'), 'billing_checkouts', ['status'], unique=False)
    op.create_index(op.f('ix_billing_checkouts_updated_at'), 'billing_checkouts', ['updated_at'], unique=False)
    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.String(length=160), nullable=True),
    sa.Column('creem_object_id', sa.String(length=180), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_events_creem_object_id'), 'billing_events', ['creem_object_id'], unique=False)
    op.create_index(op.f('ix_billing_events_event_id'), 'billing_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_billing_events_event_type'), 'billing_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_events_owner_user_id'), 'billing_events', ['owner_user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.String(length=160), nullable=False),
    sa.Column('creem_customer_id', sa.String(length=160), nullable=True),
    sa.Column('creem_subscription_id', sa.String(length=180), nullable=True),
    sa.Column('creem_product_id', sa.String(length=160), nullable=True),
    sa.Column('plan_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_creem_customer_id'), 'user_subscriptions', ['creem_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_creem_product_id'), 'user_subscriptions', ['creem_product_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_creem_subscription_id'), 'user_subscriptions', ['creem_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_current_period_end'), 'user_subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_owner_user_id'), 'user_subscriptions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_plan_key'), 'user_subscriptions', ['plan_key'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_updated_at'), 'user_subscriptions', ['updated_at'], unique=False)
    op.create_table('vedic_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(length=160), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('storage_backend', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('producer', sa.String(length=120), nullable=True),
    sa.Column('checkpointed', sa.Boolean(), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=80), nullable=True),
    sa.Column('chart_record_sha256', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'path', name='uq_vedic_artifact_session_path')
    )
    op.create_index(op.f('ix_vedic_artifacts_owner_user_id'), 'vedic_artifacts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_vedic_artifacts_session_id'), 'vedic_artifacts', ['session_id'], unique=False)
    op.create_index(op.f('ix_vedic_artifacts_updated_at'), 'vedic_artifacts', ['updated_at'], unique=False)
    op.create_table('vedic_core_job_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(length=160), nullable=True),
    sa.Column('node_id', sa.String(length=120), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('wave', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'node_id', name='uq_vedic_job_node')
    )
    op.create_index(op.f('ix_vedic_core_job_nodes_job_id'), 'vedic_core_job_nodes', ['job_id'], unique=False)
    op.create_index(op.f('ix_vedic_core_job_nodes_node_id'), 'vedic_core_job_nodes', ['node_id'], unique=False)
    op.create_index(op.f('ix_vedic_core_job_nodes_owner_user_id'), 'vedic_core_job_nodes', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_vedic_core_job_nodes_session_id'), 'vedic_core_job_nodes', ['session_id'], unique=False)
    op.create_index(op.f('ix_vedic_core_job_nodes_status'), 'vedic_core_job_nodes', ['status'], unique=False)
    op.create_index(op.f('ix_vedic_core_job_nodes_updated_at'), 'vedic_core_job_nodes', ['updated_at'], unique=False)
    op.create_table('vedic_core_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_completed', sa.Integer(), nullable=False),
    sa.Column('progress_running', sa.Integer(), nullable=False),
    sa.Column('progress_failed', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vedic_core_jobs_job_id'), 'vedic_core_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_vedic_core_jobs_owner_user_id'), 'vedic_core_jobs', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_vedic_core_jobs_session_id'), 'vedic_core_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_vedic_core_jobs_status'), 'vedic_core_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_vedic_core_jobs_updated_at'), 'vedic_core_jobs', ['updated_at'], unique=False)
    op.create_table('vedic_exports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(length=160), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('storage_backend', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'path', name='uq_vedic_export_session_path')
    )
    op.create_index(op.f('ix_vedic_exports_owner_user_id'), 'vedic_exports', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_vedic_exports_session_id'), 'vedic_exports', ['session_id'], unique=False)
    op.create_index(op.f('ix_vedic_exports_updated_at'), 'vedic_exports', ['updated_at'], unique=False)
    op.create_table('vedic_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('storage_backend', sa.String(length=30), nullable=False),
    sa.Column('storage_root', sa.Text(), nullable=False),
    sa.Column('subject_json', sa.JSON(), nullable=True),
    sa.Column('artifact_count', sa.Integer(), nullable=False),
    sa.Column('export_count', sa.Integer(), nullable=False),
    sa.Column('has_pdf', sa.Boolean(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_completed', sa.Integer(), nullable=False),
    sa.Column('progress_running', sa.Integer(), nullable=False),
    sa.Column('progress_failed', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('active_job_id', sa.String(length=80), nullable=True),
    sa.Column('active_node', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vedic_sessions_active_job_id'), 'vedic_sessions', ['active_job_id'], unique=False)
    op.create_index(op.f('ix_vedic_sessions_owner_user_id'), 'vedic_sessions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_vedic_sessions_session_id'), 'vedic_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_vedic_sessions_stage'), 'vedic_sessions', ['stage'], unique=False)
    op.create_index(op.f('ix_vedic_sessions_status'), 'vedic_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_vedic_sessions_updated_at'), 'vedic_sessions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vedic_sessions_updated_at'), table_name='vedic_sessions')
    op.drop_index(op.f('ix_vedic_sessions_status'), table_name='vedic_sessions')
    op.drop_index(op.f('ix_vedic_sessions_stage'), table_name='vedic_sessions')
    op.drop_index(op.f('ix_vedic_sessions_session_id'), table_name='vedic_sessions')
    op.drop_index(op.f('ix_vedic_sessions_owner_user_id'), table_name='vedic_sessions')
    op.drop_index(op.f('ix_vedic_sessions_active_job_id'), table_name='vedic_sessions')
    op.drop_table('vedic_sessions')
    op.drop_index(op.f('ix_vedic_exports_updated_at'), table_name='vedic_exports')
    op.drop_index(op.f('ix_vedic_exports_session_id'), table_name='vedic_exports')
    op.drop_index(op.f('ix_vedic_exports_owner_user_id'), table_name='vedic_exports')
    op.drop_table('vedic_exports')
    op.drop_index(op.f('ix_vedic_core_jobs_updated_at'), table_name='vedic_core_jobs')
    op.drop_index(op.f('ix_vedic_core_jobs_status'), table_name='vedic_core_jobs')
    op.drop_index(op.f('ix_vedic_core_jobs_session_id'), table_name='vedic_core_jobs')
    op.drop_index(op.f('ix_vedic_core_jobs_owner_user_id'), table_name='vedic_core_jobs')
    op.drop_index(op.f('ix_vedic_core_jobs_job_id'), table_name='vedic_core_jobs')
    op.drop_table('vedic_core_jobs')
    op.drop_index(op.f('ix_vedic_core_job_nodes_updated_at'), table_name='vedic_core_job_nodes')
    op.drop_index(op.f('ix_vedic_core_job_nodes_status'), table_name='vedic_core_job_nodes')
    op.drop_index(op.f('ix_vedic_core_job_nodes_session_id'), table_name='vedic_core_job_nodes')
    op.drop_index(op.f('ix_vedic_core_job_nodes_owner_user_id'), table_name='vedic_core_job_nodes')
    op.drop_index(op.f('ix_vedic_core_job_nodes_node_id'), table_name='vedic_core_job_nodes')
    op.drop_index(op.f('ix_vedic_core_job_nodes_job_id'), table_name='vedic_core_job_nodes')
    op.drop_table('vedic_core_job_nodes')
    op.drop_index(op.f('ix_vedic_artifacts_updated_at'), table_name='vedic_artifacts')
    op.drop_index(op.f('ix_vedic_artifacts_session_id'), table_name='vedic_artifacts')
    op.drop_index(op.f('ix_vedic_artifacts_owner_user_id'), table_name='vedic_artifacts')
    op.drop_table('vedic_artifacts')
    op.drop_index(op.f('ix_user_subscriptions_updated_at'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan_key'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_owner_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_current_period_end'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_creem_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_creem_product_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_creem_customer_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_billing_events_owner_user_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_event_type'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_event_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_creem_object_id'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index(op.f('ix_billing_checkouts_updated_at'), table_name='billing_checkouts')
    op.drop_index(op.f('ix_billing_checkouts_status'), table_name='billing_checkouts')
    op.drop_index(op.f('ix_billing_checkouts_request_id'), table_name='billing_checkouts')
    op.drop_index(op.f('ix_billing_checkouts_plan_key'), table_name='billing_checkouts')
    op.drop_index(op.f('ix_billing_checkouts_owner_user_id'), table_name='billing_checkouts')
    op.drop_index(op.f('ix_billing_checkouts_creem_product_id'), table_name='billing_checkouts')
    op.drop_index(op.f('ix_billing_checkouts_checkout_id'), table_name='billing_checkouts')
    op.drop_table('billing_checkouts')
    op.drop_index(op.f('ix_app_users_updated_at'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_role'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_clerk_user_id'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
